stages:
  - mirror

mirror_to_github:
  stage: mirror
  tags:
    - mirror
  script:
    - git remote remove github 2>/dev/null || true
    - git remote add github https://$GITHUB_TOKEN@github.com/GuilhermeGMV/mapa-digital-frontend.git
    - git push github HEAD:$CI_COMMIT_REF_NAME
  only:
    - main
    - develop